### PR TITLE
Upgrade node.js version

### LINKED ISSUE #41: [FEATURE] Upgrade Node.js from version 16 to version 20
### Description

Upgrade the Node.js version used by this GitHub action since the current one will be forcibly upgraded by GHA runtime.

Official docs: [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

### Screenshots

_No response_

### Additional information

GitHub Actions will automatically run using the supported version (Node.js version 20) when they remove version 16 but keeping an unsupported version in the actions generates warning messages when we run it.

### PR DESCRIPTION
**Pull request by guibranco**
## Fixes Issue

Closes #41 

## Changes proposed

Upgrade Node.js version from v16 to v20.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by guibranco** [comment]
> Stale pull request message

Still waiting for a review!

**Comment by guibranco** [comment]
@eddiejaoude could you please reopen this PR?

**Comment by eddiejaoude** [comment]
Sorry, this got lost in my long list of GitHub notifications

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Pull request merged**
